# all 
# 5000 Test_RMSE_cor = 15.56331, Test_RULscore_min = 841.13137

# partial 
# 5000 Test_RMSE_cor = 15.66810, Test_RULscore_min = 850.92948

---
gpu: '0'
save_frequency: 5
seed: 5000
task: 't1'

dist_backend: 'nccl'
world_size: -1
rank: -1
dist_url: 'tcp://224.66.41.62:23456'
multiprocessing_distributed: False
distributed: False
#dataset
data:
  root: './data'
  set: 'FD002'
  max_rul: 125
  seq_len: 30 
  num_worker: 4

#network
net:
  name: 'penet_clip'
  hand_craft: False
  input_dim: 14
  aux_dim: 4
  num_hidden: 18
  hand_dim: 28

#fedrated learning
fed:
  n_user: 5
  n_user_per_iter: 5
  train_epoch_per_step: 2
  sample_interval: 1
  iid: 'iid'

#train
train:
  resume_epoch: 0
  batch_size: 128
  lr: 0.00005
  optimizer: 'adam'
  lr_epoch: [250]
  lr_factor: 0.2
  end_epoch: 400
  callback_freq: 50
  warmup_iters: 0

# test
test:
  model_name: 'exp_lstm-0050.pth'
  model_path: './output/basic/FD002'
  test_freq: 1