# layer norm
# 3000 Test_RMSE_cor = 16.45278, Test_RULscore_min = 3413.12305
#      Test_RMSE = 16.36699, Test_RULscore = 3486.25916

#no norm
# 3000 Test_RMSE_cor = 16.55287, Test_RULscore_min = 3370.82011
---
gpu: '0'
save_frequency: 5
seed: 3000
task: 't1'

dist_backend: 'nccl'
world_size: -1
rank: -1
dist_url: 'tcp://224.66.41.62:23456'
multiprocessing_distributed: False
distributed: False
#dataset
data:
  root: './data'
  set: 'FD001'
  max_rul: 125
  seq_len: 30 
  num_worker: 4

#network
net:
  name: 'penet_clip'
  hand_craft: False
  input_dim: 14
  aux_dim: 4
  num_hidden: 18
  hand_dim: 28

#fedrated learning
fed:
  n_user: 5
  n_user_per_iter: 5
  train_epoch_per_step: 2
  sample_interval: 1
  iid: 'non_iid_v2'

#train
train:
  resume_epoch: 0
  batch_size: 128
  lr: 0.00005
  optimizer: 'adam'
  lr_epoch: [200]
  lr_factor: 0.2
  end_epoch: 300
  callback_freq: 50
  warmup_iters: 0

# test
test:
  model_name: 'exp_202110121100_cnn_pe_ep-0050.pth'
  model_path: './output/basic/FD_noniid'
  test_freq: 1