# 3000 Test_RMSE_cor = 18.76531, Test_RULscore_min = 582.73256

gpu: '0'
save_frequency: 5
seed: 3000
task: 't1'

dist_backend: 'nccl'
world_size: -1
rank: -1
dist_url: 'tcp://224.66.41.62:23456'
multiprocessing_distributed: False
distributed: False
#dataset
data:
  root: './data'
  set: 'FD001'
  max_rul: 125
  seq_len: 30 
  num_worker: 4

#network
net:
  name: 'penet_clip'
  hand_craft: False
  input_dim: 14
  aux_dim: 4
  num_hidden: 18
  hand_dim: 28

#fedrated learning
fed:
  n_user: 5
  n_user_per_iter: 2
  sample_interval: 1
  iid: 'iid'

#train
train:
  resume_epoch: 0
  batch_size: 128
  lr: 0.001
  optimizer: 'adam'
  lr_epoch: [50]
  lr_factor: 0.1
  end_epoch: 80
  callback_freq: 50
  warmup_iters: 0

# test
test:
  model_name: 'exp_lstm-0050.pth'
  model_path: './output/basic/FD001'
  test_freq: 1